apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth-apiserver.fullname" . }}
  labels:
    {{- include "oauth-apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oauth-apiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oauth-apiserver.selectorLabels" . | nindent 8 }}
        oauth-apiserver-anti-affinity: 'true'
    spec:
      serviceAccountName: {{ include "oauth-apiserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - resources:
            requests:
              cpu: 15m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          name: fix-audit-permissions
          command:
            - sh
            - '-c'
            - >-
              chmod 0770 /var/log/oauth-apiserver && touch
              /var/log/oauth-apiserver/audit.log && chmod 0600
              /var/log/oauth-apiserver/*
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: audit-log
              mountPath: /var/log/oauth-apiserver
          terminationMessagePolicy: FallbackToLogsOnError
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      containers:
        - name: oauth-apiserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - '-ec'
          args:
            - >
              if [ -s /var/run/configmaps/trusted-ca-bundle/tls-ca-bundle.pem ];
              then
                echo "Copying system trust bundle"
                cp -f /var/run/configmaps/trusted-ca-bundle/tls-ca-bundle.pem /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              fi

              exec oauth-apiserver start \
                --secure-port=8443 \
                --audit-log-path=/var/log/oauth-apiserver/audit.log \
                --audit-log-format=json \
                --audit-log-maxsize=100 \
                --audit-log-maxbackup=10 \
                --etcd-cafile=/var/run/secrets/etcd-client/ca.crt \
                --etcd-keyfile=/var/run/secrets/etcd-client/tls.key \
                --etcd-certfile=/var/run/secrets/etcd-client/tls.crt \
                --shutdown-delay-duration=10s \
                --tls-private-key-file=/var/run/secrets/serving-cert/tls.key \
                --tls-cert-file=/var/run/secrets/serving-cert/tls.crt \
                --api-audiences=https://kubernetes.default.svc \
                --audit-policy-file=/var/run/configmaps/audit/default.yaml \
                --cors-allowed-origins='//127\.0\.0\.1(:|$)' \
                --cors-allowed-origins='//localhost(:|$)' \
                --etcd-servers=https://master-01.{{ .Values.clusterDomain }}:2379 \
                --etcd-servers=https://master-02.{{ .Values.clusterDomain }}:2379 \
                --etcd-servers=https://master-03.{{ .Values.clusterDomain }}:2379 \
                --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 \
                --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 \
                --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 \
                --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 \
                --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 \
                --tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 \
                --tls-min-version=VersionTLS12 \
                --v=2
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: audit-policies
              mountPath: /var/run/configmaps/audit
            - name: etcd-client
              mountPath: /var/run/secrets/etcd-client
            - name: trusted-ca-bundle
              mountPath: /var/run/configmaps/trusted-ca-bundle
            - name: serving-cert
              mountPath: /var/run/secrets/serving-cert
            - name: encryption-config
              mountPath: /var/run/secrets/encryption-config
            - name: audit-log
              mountPath: /var/log/oauth-apiserver
      volumes:
        - name: audit-policies
          configMap:
            name: audit
            defaultMode: 420
        - name: etcd-client
          secret:
            secretName: etcd-client
            defaultMode: 420
        - name: serving-cert
          secret:
            secretName: serving-cert
            defaultMode: 420
        - name: trusted-ca-bundle
          configMap:
            name: trusted-ca-bundle
            items:
              - key: ca-bundle.crt
                path: tls-ca-bundle.pem
            defaultMode: 420
            optional: true
        - name: encryption-config
          secret:
            secretName: encryption-config
            defaultMode: 420
            optional: true
        - name: audit-log
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
